root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/app ./cmd/api"
bin = "tmp/app"
full_bin = ""
delay = 1000
include_ext = ["go"]
exclude_dir = ["tmp", "vendor", "node_modules"]
exclude_regex = ["_test.go"]
stop_on_error = true

[log]
time = true
